### PR TITLE
[FIX] Adapt home page with app router

### PR DESCRIPTION
**Pull request by Jester0027**
- Schema.org now works
- Homepage no longer crashes
- hydration issues fixed with a custom `useIsClient` hook

### CODE REVIEW

**Review by mezotv — COMMENTED** [review]
Thanks for the pull request! Ill be checking it once im at my desk.

**Review by mezotv — CHANGES_REQUESTED** [review]
The changes you made to the HomePage dont seem to make sense as most of the rendered stuff is still only rendered client side. We want to only use client side rendering where its actually needed.

**Comment by Jester0027** [comment]
> The changes you made to the HomePage dont seem to make sense as most of the rendered stuff is still only rendered client side. We want to only use client side rendering where its actually needed.

Which part is rendered on the client ?
Except from the discord components, everything should be rendered on the server.
the discord component library used seem to be using web components which are causing hydration issues

**Comment by mezotv** [comment]
> Which part is rendered on the client ? Except from the discord components, everything should be rendered on the server. the discord component library used seem to be using web components which are causing hydration issues

You can ignore the hydration errors those dont matter. The whole main component you made is client side so it should be rendered client side right?

**Comment by Jester0027** [comment]
> > Which part is rendered on the client ? Except from the discord components, everything should be rendered on the server. the discord component library used seem to be using web components which are causing hydration issues
> 
> You can ignore the hydration errors those dont matter. The whole main component you made is client side so it should be rendered client side right?

That's not exactly it:
'use server' => only executed on the server, this replaces getServerSideProps and getStaticProps.
'use client' => first rendered on the server, then on the client. Mandatory if you want to use hooks or any client side library. They basically have the same behavior as all the components in the pages directory.

So if you have a pages component with a getServerSideProps fn, getServerSideProps() should become a server component on it's own, and the corresponding component can be a hybrid component (with 'use client') or a server component **if no client side bundle is required** (e.g. no state management, fully stateless).

That's why I decided to put the 'use client' directive, this is still rendered on the server, but a client side bundle is required in order to make the framer-motion animations and all the hooks work.

**Comment by Jester0027** [comment]
I removed the hydration fix, all the content is now rendered on the server.
But it's worth taking a look at the issue though

**Comment by mezotv** [comment]
> I removed the hydration fix, all the content is now rendered on the server.
> But it's worth taking a look at the issue though

The hydration issue doesnt really matter its gonna be fixed in the newest version of their package anyways.

**Review by mezotv — CHANGES_REQUESTED** [review]
Im not a huge fan of the whole content being a component, cant we just make the ones that need to actually be a component and require data fetching/states be in one and the rest all the static stuff just be in the main. Im also not crazy about the animations so they would be removed at some point anyways.

**Comment by Jester0027** [comment]
> Im not a huge fan of the whole content being a component, cant we just make the ones that need to actually be a component and require data fetching/states be in one and the rest all the static stuff just be in the main. Im also not crazy about the animations so they would be removed at some point anyways. In case those animations make things more complex!

I don't see any problem with it being a whole component, it was in the previous version.
What you're asking here is a refactoring of the homepage, let's just keep it simple.

**Comment by mezotv** [comment]
> What you're asking here is a refactoring of the homepage, let's just keep it simple.

Fair enough then.

**Comment by Jester0027** [comment]
Hmm that's not how you're going to attract contributors.
People are giving their free time and you do this ? Really rude.

**Comment by mezotv** [comment]
> Hmm that's not how you're going to attract contributors.
> People are giving their free time and you do this ? Really rude.

My goal isnt to attract contributors I just want to rework my websites.

Your pull request does things in a way I don't want them to go so there is no point to merge your request just to revert it again soon after.

**Pull request merged**
